### ISSUE TITLE
Add autoESDA logo to the home page

### ISSUE THREAD

**Issue by NicholasDeKock** [geo-classroom/autoesda#4]
![autoesda-logo](https://user-images.githubusercontent.com/50359577/193560394-f383dd5c-90f8-41cc-ac9c-4abbd6fcbae9.png)

If possible, it would be nice to include the autoESDA logo at the top right/left of the homepage of the report. This should not distract from the rest of the report and should thus be an appropriate (small) size. The picture should also contain a hyperlink to the autoesda github repository.

**Comment by ghost** [comment]
Hi @NicholasDeKock AND @vrautenbach can I please be assigned to this issue.
