### ISSUE TITLE
Addition of an "About" page to the report

### ISSUE THREAD

**Issue by NicholasDeKock** [geo-classroom/autoesda#5]
Currently, the report has three types of pages, namely the Home/Summary page, the variable information page(s) and the correlation page. There is a need for a fourth type called the "About page" this will be located after the correlation page in the tab list at the top of the HTML report.

The About page should include information such as the date and time the report was generated, the default parameters used for each of the functions, and any other useful information.

**Comment by HluvukoMavundza** [comment]
can i please be assigned this issue

**Comment by HluvukoMavundza** [comment]
@vrautenbach  can you please assign me this issue
